export const ActionTypes = {
  GET_ALL_CANDIDATES: 'GET_ALL_CANDIDATES',
  GET_CANDIDATE: 'GET_CANDIDATE',
  GET_ALL_PARTIES: 'GET_ALL_PARTIES',
  GET_PARTY: 'GET_PARTY',
  GET_ALL_CONSTITUENCIES: 'GET_ALL_CONSTITUENCIES',
  GET_CONSTITUENCY: 'GET_CONSTITUENCY',
}
